function minicarousel(a){this.aA=a;this.aB=document.getElementById(this.aA.scrollingElementId);this.aC="vertical"==this.aA.mode?!0:!1;this.bE=void 0==this.aA.timeout?100:this.aA.timeout;this.bF();return this}
minicarousel.prototype.bF=function(){var a=this.aB.parentNode;this.aB.style.left=0;this.aB.style.top=0;this.aB.style.position="relative";var b=document.createElement("div");b.setAttribute("id","carousel_home_"+this.aA.scrollingElementId);b.style.width=this.aA.width;b.style.overflow="hidden";var c=document.createElement("div");c.setAttribute("id","carousel_wrapper_"+this.aA.scrollingElementId);c.style.width=this.aA.width;c.style.height=this.aA.height;c.style.overflow="hidden";c.appendChild(this.aB);
var e=this;this.aG=document.createElement("span");this.aG.setAttribute("id",(this.aC?"carousel_up_":"carousel_left_")+this.aA.scrollingElementId);this.aG.innerHTML=null!=this.aA.leftOrUpHTML.disabled?this.aA.leftOrUpHTML.disabled:this.aA.leftOrUpHTML.enabled;window.ActiveXObject?this.aG.style.styleFloat="left":this.aG.style.cssFloat="left";this.aG.onmouseover=function(){e.aG.style.cursor="pointer"};this.aH=document.createElement("span");this.aH.setAttribute("id",(this.aC?"carousel_down_":"carousel_right_")+
this.aA.scrollingElementId);this.aH.innerHTML=this.aA.rightOrDownHTML.enabled;window.ActiveXObject?this.aH.style.styleFloat="right":this.aH.style.cssFloat="right";this.aH.onmouseover=function(){e.aH.style.cursor="pointer"};this.aS();var d=document.createElement("div");d.setAttribute("id","carousel_header_"+this.aA.scrollingElementId);d.style.display="block";d.appendChild(this.aG);d.appendChild(this.aH);var f=document.createElement("br");f.style.clear="both";d.appendChild(f);b.appendChild(d);b.appendChild(c);
a.appendChild(b)};minicarousel.prototype.aJ=function(){return this.aC?parseInt(this.aB.style.top):parseInt(this.aB.style.left)};minicarousel.prototype.aK=function(){return this.aJ()+this.aA.amountToScroll};minicarousel.prototype.aL=function(){return this.aJ()+this.aA.amountToScroll};minicarousel.prototype.aM=function(){return this.aJ()-this.aA.amountToScroll};minicarousel.prototype.aN=function(){return this.aJ()-this.aA.amountToScroll};
minicarousel.prototype.aO=function(a){this.aC?this.aB.style.top=a+"px":this.aB.style.left=a+"px"};minicarousel.prototype.aP=function(){return parseInt(this.aA.amountToScroll)-parseInt(this.aB.style.width)};minicarousel.prototype.aQ=function(){return parseInt(this.aA.amountToScroll)-parseInt(this.aB.style.height)};minicarousel.prototype.aR=function(){this.aG.onclick=null;this.aH.onclick=null};
minicarousel.prototype.aS=function(){var a=this;this.aH.onclick=this.aC?function(){a.aY(a.aN())}:function(){a.aX(a.aM())};this.aG.onclick=this.aC?function(){a.bA(a.aL())}:function(){a.aZ(a.aK())}};minicarousel.prototype.aT=function(){null!=this.aA.leftOrUpHTML.disabled&&(this.aG.innerHTML=this.aA.leftOrUpHTML.disabled)};minicarousel.prototype.aU=function(){this.aG.innerHTML=this.aA.leftOrUpHTML.enabled};
minicarousel.prototype.aV=function(){null!=this.aA.rightOrDownHTML.disabled&&(this.aH.innerHTML=this.aA.rightOrDownHTML.disabled)};minicarousel.prototype.aW=function(){this.aH.innerHTML=this.aA.rightOrDownHTML.enabled};minicarousel.prototype.aX=function(a){var b=this.aJ();this.aR();this.aU();if(b==this.aP())this.aS(),this.aV();else if(this.bC(a,b),!this.bD(b,a)){var c=this;timer=setTimeout(function(){c.aX(a)},this.bE)}};
minicarousel.prototype.aY=function(a){var b=this.aJ();this.aR();this.aU();if(b==this.aQ())this.aS(),this.aV();else if(this.bC(a,b),!this.bD(b,a)){var c=this;timer=setTimeout(function(){c.aY(a)},this.bE)}};minicarousel.prototype.aZ=function(a){var b=this.aJ();this.aR();this.aW();if(0==b)this.aS(),this.aT();else if(this.bB(a,b),!this.bD(b,a)){var c=this;timer=setTimeout(function(){c.aZ(a)},this.bE)}};
minicarousel.prototype.bA=function(a){var b=this.aJ();this.aR();this.aW();if(0==b)this.aS(),this.aT();else if(this.bB(a,b),!this.bD(b,a)){var c=this;timer=setTimeout(function(){c.bA(a)},this.bE)}};minicarousel.prototype.bB=function(a,b){var c=Math.abs(a)-Math.abs(b);this.aO(b-Math.floor(c/2))};minicarousel.prototype.bC=function(a,b){var c=Math.abs(a)-Math.abs(b);this.aO(b-Math.ceil(c/2))};minicarousel.prototype.bD=function(a,b){return a==b?(clearTimeout(timer),this.aS(),!0):!1};
